sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: 
    access-key-secret: 
    bucket-name: storage-wm

  redis:
    host: 192.168.50.128
    port: 6379
    database: 10

  wechat:
    appid: wx6c435f3878a064d0
    secret: 5a0306bf47107d74ff7c849d9e69fe2a
