sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tByNitN3CLNcfssvdHe
    access-key-secret: cFWJc1mDL7U4SlfymxC62xhpWTJ3mg
    bucket-name: storage-wm

  redis:
    host: 192.168.50.128
    port: 6379
    database: 10
